name:                presentable
version:             0.1.0.0
github:              "sjpeterson/presentable"
license:             MIT
author:              "Stefan Peterson"
maintainer:          "stefan.j.peterson@gmail.com"
copyright:           "2022 Stefan Peterson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sjpeterson/presentable#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - brick
  - megaparsec
  - microlens
  - mtl
  - text
  - vty
  ghc-options:
    - -W

executables:
  presentable:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W
    dependencies:
    - optparse-applicative
    - presentable

tests:
  presentable-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - presentable
    - text
