name:                presentable
version:             0.2.0
github:              "sjpeterson/presentable"
license:             MIT
author:              "Stefan Peterson"
maintainer:          "stefan.j.peterson@gmail.com"
copyright:           "2022 Stefan Peterson"
synopsis:            A program for running minimalist presentations in the terminal
category:            Presentation
description:         Please see the README on GitHub at <https://github.com/sjpeterson/presentable#readme>

extra-source-files:
- README.md
- ChangeLog.md


dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - brick
  - directory
  - filepath
  - megaparsec
  - microlens
  - microlens-th
  - mtl
  - parser-combinators
  - text
  - vty
  - yaml
  ghc-options:
    - -W

executables:
  presentable:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W
    dependencies:
    - optparse-applicative
    - presentable

tests:
  presentable-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - presentable
    - text
